### ISSUE TITLE
Getting issue Failed to create dialer., OriginalError: %!w(*fmt.wrapError=&{failed to dial: failed to open connection to

### ISSUE THREAD

**Issue by kusumkappdirect** [mostafa/xk6-kafka#122]
```javascript
import { check } from "k6";

import { Writer, Connection, TLS_1_2 } from "k6/x/kafka"; // import kafka extension

import {configuration} from "./configuration.js";

const bootstrapServers = [__ENV.KAFKA_BOOTSTRAP_SERVERS];
const topic = "billing-invoices-v3-load-test.itg-load.default";

const username = __ENV.KAFKA_USERNAME;
const password = __ENV.KAFKA_PASSWORD;

// console.log("Username"+username);
// console.log("Password"+password);
//
const saslConfig = {
    username: username,
    password: password,
    algorithm: "sasl_ssl",
};

const tlsConfig = {
    enableTLS: true,
    insecureSkipTLSVerify: true,
    minVersion: TLS_1_2,
};
//const [producer,_writerError] = writer(bootstrapServers, topic, saslConfig, tlsConfig);


const writer = new Writer({
    brokers: bootstrapServers,
    topic: topic,
    sasl: saslConfig,
    tls: tlsConfig,
});

const connection = new Connection({
    address: bootstrapServers[0],
    sasl: saslConfig,
    tls: tlsConfig,
});
```

then a value schema i created.
```javascript
  let error =  writer.produce({
            messages: messages,
             config: configuration,
            valueSchema: valueSchema,
        });
        check(error, {
            "is sent": (err) => err == undefined,
        });
```

configuration looks like :
```javascript
import { AVRO_SERIALIZER } from "k6/x/kafka"; // import kafka extension

export var configuration = JSON.stringify({
    producer: {
        keySerializer: "",
        valueSerializer: AVRO_SERIALIZER,
    },
    schemaRegistry: {
        url: __ENV.KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
    },
});
```

what is wrong here ?

**Comment by kusumkappdirect** [comment]
After changing     let error =  writer.produce({
            messages: messages,
             config: configuration,
            keySchema: "null",
            valueSchema: valueSchema
        }); 
        
Getting new error ..
          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: ./invoiceevent.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

time="2022-07-12T08:47:28Z" level=error msg="json: cannot unmarshal string into Go struct field ProduceConfig.config of type kafka.Configuration\n\tat github.com/mostafa/xk6-kafka.(*Kafka).XWriter.func1 (native)\n\tat file:///app/invoiceevent.js:2351:25(876)\n\tat native\n" executor=per-vu-iterations scenario=default source=stacktrace

running (00m00.1s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  00m00.0s/10m0s  1/1 iters, 1 per VU

     █ teardown

     data_received........: 0 B 0 B/s
     data_sent............: 0 B 0 B/s
     iteration_duration...: avg=1.09ms min=82.23µs med=1.09ms max=2.11ms p(90)=1.91ms p(95)=2.01ms
     iterations...........: 1   11.191392/s

**Comment by mostafa** [comment]
@kusumkappdirect Of course!
https://github.com/mostafa/xk6-kafka#install-and-build-the-latest-tagged-version

**Comment by kusumkappdirect** [comment]
ok

**Comment by kusumkappdirect** [comment]
ok..i am testing with argo-cd ,i will give update on it

**Comment by kusumkappdirect** [comment]
Its worked , but i have a question , when my producer created with argo-cd 

`{{ if .Values.kafka.enabled }}
apiVersion: kafka.appdirect.com/v1alpha1
kind: Producer
metadata:
  name: itg-load
  namespace: {{ .Values.namespace }}
spec:
  topics:
    - name: billing-invoices-v3-load-test.itg-load.{{ .Values.namespace }}
      partitions: 10
  {{ end }}`


and a schema validator used to validate the schema 

` imagePullPolicy: Always
          args:
            - publish
            - com.invoice.events.avro.v3.UnitDiscount=github.com/invoice-core//invoice-event/src/main/resources/com/invoice/events/avro/v3/UnitDiscount.avsc?ref=master
            - `
topic created when producer created with schema which provided here..

when we are running are script which is looks like  this.

`"fields": [
    {
      "name": "eventMetadata",
      "type": {
        "fields": [ 
          {
            "name": "id",
            "type": {
              "avro.java.string": "String",
              "type": "string"
            }
          },
          {
            "name": "timestamp",
            "type": {
              "avro.java.string": "String",
              "type": "string"
            }
          },
          {
            "name": "type",
            "type": {
              "avro.java.string": "String",
              "type": "string"
            }
          },
          {
            "default": null,
            "name": "operation",
            "type": [
              "null",
              {`


this new schema upgrade the existing one..can i skip it , if yes, which method should i use to send message ?

**Comment by mostafa** [comment]
@kusumkappdirect 
Currently the schema is automatically fetched, and you can't control this.
