### ISSUE TITLE
Getting error at TypeError: Value is not an object: undefined

### ISSUE THREAD

**Issue by kusumkappdirect** [mostafa/xk6-kafka#128]
At this line getting error .const srClient = SchemaRegistryClientWithConfiguration(configuration.schemaRegistry);

```


          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: ./invoiceevent.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

time="2022-07-13T10:05:26Z" level=error msg="TypeError: Value is not an object: undefined\n\tat file:///app/invoiceevent.js:1768:59(7)\n\tat native\n" executor=per-vu-iterations scenario=default source=stacktrace

running (00m00.3s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  00m00.0s/10m0s  1/1 iters, 1 per VU

     █ teardown

     data_received........: 0 B 0 B/s
     data_sent............: 0 B 0 B/s
     iteration_duration...: avg=45.24µs min=20.62µs med=45.24µs max=69.86µs p(90)=64.93µs p(95)=67.39µs
     iterations...........: 1   3.333166/s

```

**Comment by kusumkappdirect** [comment]
@mostafa

**Comment by kusumkappdirect** [comment]
@mostafa  , how can  i fetch the schemas from the schema registery then. ?

**Comment by mostafa** [comment]
By passing this `schemaRegistry` object to [config](https://github.com/mostafa/xk6-kafka/blob/main/docs/interfaces/Configuration.md) object in `ProduceConfig`.

**Comment by kusumkappdirect** [comment]
Is this is done ?https://github.com/mostafa/xk6-kafka/issues/125

**Comment by kusumkappdirect** [comment]
Can you please help me @mostafa , how can i send message, which method should i use, if producer already created, topic already present , schema already created with help of argo-cd.
Our condition is to use sasl_ssl and tls should be enable

const saslConfig = {
    username: username,
    password: password,
    algorithm: "sasl_ssl",
};

const tlsConfig = {
    enableTLS: true,
    insecureSkipTLSVerify: true,
    minVersion: TLS_1_2,
};

**Comment by mostafa** [comment]
These features need to be present, and you need to either wait or sponsor the project if you want those parts sooner:
https://github.com/mostafa/xk6-kafka/issues/122#issuecomment-1181674370
