### ISSUE TITLE
No exceptions thrown on message submission/producing failure

### ISSUE THREAD

**Issue by jpan7994** [mostafa/xk6-kafka#156]
I think [this bug](https://github.com/mostafa/xk6-kafka/blob/0658903da9b79e9d9a4bdc808865797d3fa18677/writer.go#L253) was introduced by [this commit](https://github.com/mostafa/xk6-kafka/pull/149). The change causes an exception to be raised only when the context is cancelled, but no exceptions are raised for any other failure, e.g., wrong SSL/TLS protocol version.

**Comment by mostafa** [comment]
Hey @jpan7994,

Thanks for reporting this. 🙏 I think the fix would be quick.
