### ISSUE TITLE
How to add headers to producer?

### ISSUE THREAD

**Issue by AdiTasa** [mostafa/xk6-kafka#17]
Hey,
I want to add headers, can you share an example please?

By the way, very helpful extension :)

**Comment by mostafa** [comment]
Hey @AdiTasa,

The producer doesn't support headers right now. I'll try to add the feature when I find some free time.

**Comment by mostafa** [comment]
@AdiTasa 
Do you want to add headers to messages produced? If so, #46 adds the feature.

**Comment by mostafa** [comment]
@AdiTasa The feature is merged, and you can test it if you build the `main` branch manually. I'll release it eventually after some more testing.

BTW, I'll close this ticket. Feel free to reopen it if you have any other questions or feedback or think this issue hasn't been resolved yet.
