### ISSUE TITLE
Partitions on a group doesnt work

### ISSUE THREAD

**Issue by dgarcas** [mostafa/xk6-kafka#172]
I would like to make a topic with the same partitions as VUs running. Then I woul like to run another script that consumes from this topic, this script will run VUs as much as partitions or even more. 
But normally I am no able to consume with all the vus from each partition even when I set the partition for each reader.

**Comment by dgarcas** [comment]
Jus one VU can consume and the rest stop the execution when they made the consume

**Comment by mostafa** [comment]
Hey @dgarcas,

Can you give me an example of the scripts you use and the commandline options you pass to k6? Please remove any confidential info from it, I just need the syntax you used.

**Comment by dgarcas** [comment]
The reader code, I use three, but they looks like this: 

`import {check} from 'k6';
import ws from 'k6/ws';
import {SCHEMA_TYPE_JSON} from "k6/x/kafka";

import {post_IMChat} from './im/httpRequester.js';
import {runIMWS} from './im/WebsocketIM.js'
import {psap_connections, psap_eds_managed} from '../../../../../common/model/metrics/Metrics.js';

import {Connection, SchemaRegistry, SCHEMA_TYPE_STRING} from "k6/x/kafka";
import {Writer, Reader} from "k6/x/kafka";

const brokerAddress = "kafka:9092",  imTopic = "IM";
const data = JSON.parse(open('../../../../resources/config/settings.json'));

const connection = new Connection({
    address: brokerAddress,
});

if (__VU == 0) {
    connection.createTopic({
        topic: imTopic,
        numPartitions: parseInt(JSON.stringify(data.total_aps)),
    });
}

console.log(`creando topic para __VU ${__VU} con particion: ${__VU == 0 ? 100000000 : __VU - 1}`)
const reader = new Reader({
    brokers: [brokerAddress],
    topic: imTopic,
    partition: __VU == 0 ? 100000000 : __VU - 1,
});

const schemaRegistry = new SchemaRegistry(
)

export function executePsap(data) {
    console.info(`PSAP [VU: ${__VU} | ITER: ${__ITER}]: IM`);

    psap_connections.add(1, {capability: "IM"});
    enableIM(data);
}
function enableIM(data) {
    let edsId = getEds();

    if (edsId !== undefined) {
        psap_eds_managed.add(1, {id: edsId, capability: "IM"});
        let response = post_IMChat(edsId, data);

        if (response.status == 200) {
            let body = JSON.parse(response.body);
            let params = {headers: {Authorization: body.token}, tags: {component: "PSAP", capability: "IM"}};

            let res = ws.connect(body.uri, params, runIMWS);
            check(res, {'PSAP HTTP response of WS connection 101': (r) => r && r.status === 101});
        }
    }
}

function getEds() {
    let message = reader.consume({limit: 1});
    let value = getValueDeserialized(message[0]);
    let id = value.eds;
    console.info(`PSAP [VU: ${__VU} | ITER: ${__ITER}]: EDS pulled: ${id}`);

    return id;
}

function getValueDeserialized(message) {
    return schemaRegistry.deserialize({
        data: message.value,
        schemaType: SCHEMA_TYPE_JSON,
    })
}

export function closeBroker() {
    connection.deleteTopic(imTopic);
    reader.close();
    connection.close();
}`

The writter who writes to the rest three kind of readres: 
`import {sleep} from 'k6';
import {
    ap_messages_received, ap_messages_sent, ap_time_establish_connection, ap_time_found_psap, ap_time_establish_call,
    ap_messages_error, delivery_fail_response_ms, established_fail_response_ms
} from '../../../../../../../common/model/metrics/Metrics.js'
import {schemas, CLOSE, SETUP} from '../../../../model/SchemaManager.js'
import {times} from "./wsCaller.js";
import {location_update_timer} from "../capabilities/locationUpdate/LocationUpdateTimmer.js";
import {
    ghale_ap_requested_sessions_count_total,
    ghale_ap_available_capabilities_count_total,
    ghale_ap_eds_dispatched_count_total,
    ghale_ap_call_establishment_millis,
    ghale_ap_call_establishment_millis_max,
    ghale_ap_call_duration_millis,
    ghale_ap_call_duration_millis_max
} from "../../../../../../../common/model/metrics/ap/APMetrics.js";

import { Writer, Reader, Connection, SchemaRegistry, SCHEMA_TYPE_STRING, SCHEMA_TYPE_JSON } from "k6/x/kafka";

export let edsID;
export let edsToDelete = []
const schemaRegistry = new SchemaRegistry();
const brokerAddress = "kafka:9092",  locationUpdateTopic = "LOCATION_UPDATE", imTopic = "IM", rttTopic = "RTT";
const data = JSON.parse(open('../../../../../resources/config/settings.json'));

const connection = new Connection({
    address: "kafka:9092",
});

if (__VU == 0) {
    connection.createTopic({
        topic: locationUpdateTopic,
        numPartitions: parseInt(JSON.stringify(data.total_aps)),
    });

    connection.createTopic({
        topic: imTopic,
        numPartitions: parseInt(JSON.stringify(data.total_aps)),
    });

    connection.createTopic({
        topic: rttTopic,
        numPartitions: parseInt(JSON.stringify(data.total_aps)),
    });
}

const writerTopicLocation = new Writer({
    brokers: [brokerAddress],
    topic: locationUpdateTopic,
});
const writerTopicRTT = new Writer({
    brokers: [brokerAddress],
    topic: rttTopic,
});
const writerTopicIM = new Writer({
    brokers: [brokerAddress],
    topic: imTopic,
});


export function establishManage(socket, parsedData) {

    edsID = parsedData.sessionId;
    edsToDelete.push(parsedData.sessionId)

    if (parsedData.result == 'SUCCESS') {
        times.time_establish_success = Date.now();
        ap_time_establish_connection.add(times.time_establish_success - times.time_setup);
        ghale_ap_call_establishment_millis.add(times.time_establish_success - times.time_setup, {result: 'success'});
        ghale_ap_call_establishment_millis_max.add(times.time_establish_success - times.time_setup, {result: 'success'});
        ghale_ap_requested_sessions_count_total.add(1, {result: 'success'});
        console.debug(`AP [VU: ${__VU} | ITER: ${__ITER}]  ESTABLISHED_SUCCESS: ${parsedData.sessionId}`);
        ap_messages_received.add(1, {capability: "routing", type: "ESTABLISHED_SUCCESS"});


    } else if (parsedData.result == 'FAIL') {
        established_fail_response_ms.add(times.time_establish_success - times.time_setup);
        ghale_ap_call_establishment_millis.add(times.time_establish_success - times.time_setup, {result: 'fail'});
        ghale_ap_call_establishment_millis_max.add(times.time_establish_success - times.time_setup, {result: 'fail'});

        console.error(`AP [VU: ${__VU} | ITER: ${__ITER}] | edsID: ${parsedData.sessionId} ESTABLISHED_FAIL`);
        ap_messages_received.add(1, {capability: "routing", type: "ESTABLISHED_FAIL"});
        ghale_ap_requested_sessions_count_total.add(1, {result: 'fail'});

        console.info(`AP [VU: ${__VU} | ITER: ${__ITER}] send CLOSE`);
        socket.send(schemas[CLOSE]);
        ap_messages_sent.add(1, {capability: "routing", type: "CLOSE"});

        sleep(100);
        socket.close();

        ghale_ap_call_duration_millis.add(Date.now() - times.time_establish_success);
        ghale_ap_call_duration_millis_max.add(Date.now() - times.time_establish_success);
    }
}

export function deliverySuccessManage(socket, parsedData) {
    times.time_delivery_success = Date.now();
    ap_time_found_psap.add(times.time_delivery_success - times.time_establish_success);
    ap_time_establish_call.add(times.time_delivery_success - times.time_setup);
    ghale_ap_eds_dispatched_count_total.add(1, {result: 'success'});

    let message = {
        messages: [
            {
                value: schemaRegistry.serialize({
                    data: {
                        eds: edsID,
                        status: "OPEN"
                    },
                    schemaType: SCHEMA_TYPE_JSON,
                }),
            },
        ],
    }
    writerTopicLocation.produce(message);
    writerTopicIM.produce(message);
    writerTopicRTT.produce(message);

    ap_messages_received.add(1, {capability: "routing", type: "DELIVERY_SUCCESS"});

    enableLocationUpdateTimmer(socket);
    countTimesCapabilityHasBeenAvailable(parsedData);
}

function enableLocationUpdateTimmer(socket) {
    location_update_timer(socket);
}

function countTimesCapabilityHasBeenAvailable(parsedData) {
    for (const capability in parsedData.capabilities) {
        ghale_ap_available_capabilities_count_total.add(1, {capability_type: capability});
    }
}


export function deliveryFailManage(socket) {
    ap_messages_received.add(1, {capability: "routing", type: "DELIVERY_FAIL"});
    delivery_fail_response_ms.add(Date.now() - times.time_establish_success);
    ghale_ap_eds_dispatched_count_total.add(1, {result: 'success'});

    console.error(`AP [VU: ${__VU} | ITER: ${__ITER}] | edsID: ${edsID} DELIVERY_FAIL `);
    console.info(`AP [VU: ${__VU} | ITER: ${__ITER}]  send CLOSE`);

    socket.send(schemas[CLOSE]);
    ap_messages_sent.add(1, {capability: "routing", type: "CLOSE"});
    sleep(100);
    socket.close();

    ghale_ap_call_duration_millis.add(Date.now() - times.time_establish_success);
    ghale_ap_call_duration_millis_max.add(Date.now() - times.time_establish_success);
}

export function errorManage(socket, parsedData) {
    console.error(`AP [VU: ${__VU} | ITER: ${__ITER}] | edsID: ${edsID}: ${JSON.stringify(parsedData)}`);
    ap_messages_error.add(1, {capability: "routing", statusCode: parsedData.code, reason: parsedData.reason});

    socket.send(schemas[CLOSE]);
    ap_messages_sent.add(1, {capability: "routing", type: "CLOSE"});
    sleep(100);
    socket.close();

    ghale_ap_call_duration_millis.add(Date.now() - times.time_establish_success);
    ghale_ap_call_duration_millis_max.add(Date.now() - times.time_establish_success);
}

export function defaultManage(socket) {
    console.error(`AP [VU: ${__VU} | ITER: ${__ITER}] | edsID: ${edsID} Unknown message. Send CLOSE.`);
    console.error(`AP [VU: ${__VU} | ITER: ${__ITER}] | edsID: ${edsID}: ${data}`);
    ap_messages_error.add(1, {capability: "routing", reason: "Unknown message"});

    socket.send(schemas[CLOSE]);
    ap_messages_sent.add(1, {capability: "routing", type: "CLOSE"});
    sleep(100);
    socket.close();

    ghale_ap_call_duration_millis.add(Date.now() - times.time_establish_success);
    ghale_ap_call_duration_millis_max.add(Date.now() - times.time_establish_success);
}

export function closeBroker() {
    connection.deleteTopic(locationUpdateTopic);
    connection.deleteTopic(imTopic);
    connection.deleteTopic(rttTopic);

    writerTopicLocation.close();
    writerTopicIM.close();
    writerTopicRTT.close();

    connection.close();
}





`

**Comment by dgarcas** [comment]
[kafka.zip](https://github.com/mostafa/xk6-kafka/files/9838629/kafka.zip)
Here you can see it cearly

**Comment by mostafa** [comment]
@dgarcas
You need to use a [groupID](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/ReaderConfig.md#groupid) in your reader to consume from. When you specify a `groupID`, you don't need a partition anymore.

**Comment by mostafa** [comment]
@dgarcas 
I'll close this ticket due to inactivity. Feel free to re-open it if the issue persists.
