### ISSUE TITLE
prometheus metrics are not compatible with "dots"

### ISSUE THREAD

**Issue by rgordill** [mostafa/xk6-kafka#176]
Hi.

This component creates metrics with dot as separator (see for example https://github.com/mostafa/xk6-kafka/blob/main/stats.go#L61). However, it is not compatible with prometheus metrics (https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels), so underscore should be used as separator (see the metrics exposed by k6: https://k6.io/docs/using-k6/metrics/).

Thanks.

**Comment by mostafa** [comment]
Hey @rgordill,

There original reason for this naming convention is its usage in kafka-go for [reader](https://github.com/segmentio/kafka-go/blob/eba9cae7fd57401a8078f6f25bc00cb753cd4f42/reader.go#L572-L604) and [writer](https://github.com/segmentio/kafka-go/blob/eba9cae7fd57401a8078f6f25bc00cb753cd4f42/writer.go#L345-L386) stats. But I have no strong opinion about keeping it as is.

**Comment by mostafa** [comment]
@rgordill 
I'll keep the changes on the main branch for a day or two and then I'll release it with a new version (tag).

**Comment by rgordill** [comment]
♥‿♥

**Comment by mostafa** [comment]
Released in [v0.16.0](https://github.com/mostafa/xk6-kafka/releases/tag/v0.16.0).
