### ISSUE TITLE
Unclear metrics

### ISSUE THREAD

**Issue by gpiechnik2** [mostafa/xk6-kafka#184]
From my point of view, the metrics made available in the summary are unclear. For example:

```
kafka_reader_fetch_bytes - Total bytes the reader fetches batches of messages from Kafka.
```

I understand that since `kafka_reader_fetch_bytes ` is the amount in bytes, what is `kafka_reader_fetch_size`?

Is it possible to add to the documentation information about the returned metrics? Something similar was [attempted](https://k6.io/blog/load-test-your-kafka-producers-and-consumers-using-k6/) by k6 developers, while the post is already outdated.

**Comment by mostafa** [comment]
Hey @gpiechnik2,

Thanks for the suggestion! I'd like to update the article and add more docs, but I need to find the time.

**Comment by mostafa** [comment]
@gpiechnik2 

I added a table explaining metrics as best as I can in #189. It'll be eventually merged.

**Comment by mostafa** [comment]
Hey @gpiechnik2,

The description of [emitted metrics](https://github.com/mostafa/xk6-kafka#emitted-metrics) and their types are added to the README.
