### ISSUE TITLE
Support for AWS IAM authentication

### ISSUE THREAD

**Issue by gokceyalcin** [mostafa/xk6-kafka#191]
It seems testing against AWS MSK cluster deployments is not possible without the IAM authentication support.

I made a PR, although feel free to salvage & fit in with JS usage. Since the configuration passed from JS is specific to SASL and TLS only, I introduced the option as an environment variable. 

PR here: https://github.com/mostafa/xk6-kafka/pull/190

**Comment by mostafa** [comment]
@gokceyalcin 

Awesome! Thanks for your contribution. I'll have a look tomorrow and will fix the JS specific parts, if needed.

**Comment by mostafa** [comment]
@gokceyalcin Can you please test the changes in #193 on your system?

**Comment by mostafa** [comment]
@gokceyalcin Can you please confirm that it works as expected?
