### ISSUE TITLE
v0.16.1 seems to be missing the java script code

### ISSUE THREAD

**Issue by ttekampe** [mostafa/xk6-kafka#192]
When I compile a custom k6 executable that includes the kafka extension like this
```
 xk6 build --with github.com/mostafa/xk6-kafka@latest --output k6kafka
```
where latest today is `v0.16.1`, my test scripst fail as the objects imported from `k6/x/kafka` are undefined.

This does not happen if I use `v0.16.0` like so:
```
xk6 build --with github.com/mostafa/xk6-kafka@v0.16.0 --output k6kafka
```

**Comment by mostafa** [comment]
@ttekampe 

I think you are using the wrong binary. I just ran the same command locally and was able to run the scripts. Do you run this command after building xk6-kafka with xk6?
```bash
./k6kafka run scripts/test_json.js
```

**Comment by mostafa** [comment]
@ttekampe 

Is your problem solved?

**Comment by ttekampe** [comment]
Sorry for not getting back quicker.

Yes the problem is solved. The imports work now, thanks
