### ISSUE TITLE
Timeout when the reader cannot consume messages anymore

### ISSUE THREAD

**Issue by mostafa** [mostafa/xk6-kafka#196]
Due to several reports in #180, I need to introduce an external context with timeout to prevent `reader.consume` from hanging.

**Comment by JasmineCA** [comment]
Hello. First, thanks for your extension! Currently this is the only one to work with kafka in k6 script! Do you plan to work on this bug soon? This is very annoying in my project when some kafka messages are not received randomly, the test hangs until k6 reaches the end of the test duration time. I'm not really skilled with writting extensions for kafka yet (only wrote an extension to do some custom crypto operations and keep keys) so definitely I have no idea about adding a timeout in the context to make it work.

**Comment by JasmineCA** [comment]
Hello @mostafa , do you have any update on this?
