### ISSUE TITLE
Invalid session timeout

### ISSUE THREAD

**Issue by carlostancinco** [mostafa/xk6-kafka#197]
Hi @mostafa
I have a Kafka-enabled event hub in Azure. However, when I try to initialize the reader with groupID and sessionTimeout, the following error occurs:
`"Failed to join group test-group: [26] Invalid Session Timeout: the requested session timeout is outside of the allowed range on the broker"`
Is there a particular value that wouldn't work with sessionTimeout? I have tried multiple values for it and always get this error. I am curious whether specifying both groupID and sessiontTimeout has worked with anyone, or whether there is an error on my part. Below is my script, thanks in advance.
```
import {
  Reader,
  Connection,
  SASL_SSL,
  TLS_1_2,
} from "k6/x/kafka";

const brokers = ["mynamespace.servicebus.windows.net:9093"];
const topic = "test-topic";

const saslConfig = {
  username: "$ConnectionString",
  password: "{YOUR.EVENTHUBS.CONNECTION.STRING}",
  algorithm: SASL_SSL,
};

const tlsConfig = {
  enableTls: true,
  insecureSkipTlsVerify: false,
  minVersion: TLS_1_2,
};

const reader = new Reader({
  brokers: brokers,
  groupID: "test-group",
  groupTopics: [topic],
  sasl: saslConfig,
  tls: tlsConfig,
  connectLogger: true,
  sessionTimeout: 30000,
});

const connection = new Connection({
  address: brokers[0],
  sasl: saslConfig,
  tls: tlsConfig,
});

export default function () {
	let messages = reader.consume({ limit: 1 });
	let result = JSON.stringify(messages);
	console.log(result);
} 
```

**Comment by carlostancinco** [comment]
Also, default session timeout produces the same error. Appreciate any suggestions.

**Comment by mostafa** [comment]
Hey @carlostancinco,

Can you try to set `rebalanceTimeout`? It can't be lower than `sessionTimeout` and it seems that the error originates from that, as also suggested [here](https://stackoverflow.com/a/58422760/6999563).

**Comment by carlostancinco** [comment]
Yes, I also tried with the rebalanceTimeout and made sure it's not lower that sessionTimeout. Still the error is coming.

**Comment by mostafa** [comment]
The timeout values should be in billions. That is, it should be in golang format, where `1000000000` == 1s. So, 30000 means 30 microseconds.

**Comment by carlostancinco** [comment]
So I changed my timeout (both session and rebalance) values in billions and it worked. Initially I thought I was already putting the values in seconds. Thank you for your help.

**Comment by mostafa** [comment]
Glad it worked.
