### ISSUE TITLE
Support for SASL authentication

### ISSUE THREAD

**Issue by natwie** [mostafa/xk6-kafka#2]
Hi Mostafa! Does the k6 kafka library support SASL authentication, for example, SASL/SCRAM?

**Comment by mostafa** [comment]
hey @natwie,

Currently it doesn't support SASL authentication. But I'll add it very soon.

**Comment by mostafa** [comment]
Hey @natwie,

Have you had any luck in testing the PR #3?

**Comment by SamuelleMollard** [comment]
Hello, as I mentioned on the PR I am able to help you if I can be of any use.
I don't want to just come and do things other people are already doing, but if you need me to test the PR, or anything else I can definitely give you a hand

**Comment by mostafa** [comment]
Hey @SamuelleMollard,

I'd be happy and delighted if you can test this feature (the PR) and report any issues. I spent some time trying to figure out a configuration for ZooKeeper and Kafka for this feature, but to no avail. Also, I haven't tested it with the new ZooKeeper-less Kafka, which might be easier to configure for SASL authentication, I guess. I'll update the PR for your testing.

**Comment by SamuelleMollard** [comment]
Very well, I'm starting

**Comment by mostafa** [comment]
I updated the PR. Just checkout the branch and run `xk6 build --with github.com/mostafa/xk6-kafka=.`.

**Comment by SamuelleMollard** [comment]
Thanks

**Comment by mostafa** [comment]
Hey @sniku, @natwie and @SamuelleMollard!

I was finally able to test this feature with Kafka with SASL PLAIN and SASL SCRAM enabled, which I have documented in [this commit message](https://github.com/mostafa/xk6-kafka/pull/3/commits/216ee0cd4f69864cb259445819541ef34fe2f2dd). The SASL SSL is not supported yet and would be a future PR.

Also, I wasn't able to test the script from outside the container and I suspect it was related to docker networking, but if you have a Kafka instance hosted somewhere over the internet, I think it should be fine.

I'd be happy to hear your feedback.

**Comment by mostafa** [comment]
The [feature](https://github.com/mostafa/xk6-kafka/pull/3) is merged, so I close this ticket.

**Comment by SamuelleMollard** [comment]
Yeah, sorry for my lack of answers, it's all good with me

**Comment by SamuelleMollard** [comment]
Didn't get to do much testing though, sorry about that

**Comment by mostafa** [comment]
No worries!
