### ISSUE TITLE
How to use autocompletion in IDEs?

### ISSUE THREAD

**Issue by fl0wx** [mostafa/xk6-kafka#200]
hey i just wondered how i can make use of autocompletion like i can do it with base k6 via adding "@types/k6": "^0.42.0" to devDependencies. Is that possible with k6 kafka? 
Thanks and regards,
fl0w

**Comment by mostafa** [comment]
Hey @fl0wx,

AFAIK, you can copy the [`index.d.ts`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/index.d.ts) file into your project directory and reference it in your script to get auto-completion:
```javascript
/// <reference path="index.d.ts" />

...
```

**Comment by fl0wx** [comment]
> Hey @fl0wx,
> 
> AFAIK, you can copy the [`index.d.ts`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/index.d.ts) file into your project directory and reference it in your script to get auto-completion:
> 
> ```js
> /// <reference path="index.d.ts" />
> 
> ...
> ```

thanks that works :)
