### ISSUE TITLE
Error writing messages to [topic_name] kafka.(*Client).Produce: context deadline exceeded

### ISSUE THREAD

**Issue by atlok** [mostafa/xk6-kafka#202]
config.json
```json
{
  "scenarios": {
    "constant_request_rate": {
      "executor": "constant-arrival-rate",
      "rate": 100,
      "timeUnit": "1s",
      "duration": "30s",
      "preAllocatedVUs": 100,
      "maxVUs": 200
    }
  }
}
```

orderPaidScenario.js
```javascript
import OrderManager from '../common/orderManager/OrderManager.js'
import OrderPaidNotify from "../common/kafka/exchanges/OrderPaidNotify.js"


const testConfig = JSON.parse(open('../config/test.json'))
const orderPaidNotify = new OrderPaidNotify()


export const options = Object.assign({

}, testConfig);


export default function () {
    const order = new OrderManager().create()
    orderPaidNotify.orderPaid(order.data.order_id, order.data.items)

    console.log('OrderID: ', order.data.order_id)

}
```

Producer:

```javascript
import { Writer, SchemaRegistry, SCHEMA_TYPE_STRING} from "k6/x/kafka";


export default class Producer {
    constructor(topic) {
        this.client = this.resolveProducerClient(topic)
        this.schemaRegistry = new SchemaRegistry()
    }

    resolveProducerClient(topic) {
        return new Writer({
            brokers: [
                'localhost:9092'
            ],
            topic: topic,
            autoCreateTopic: true,
            connectLogger: true,
            maxAttempts: 10,
            readTimeout: 1000
        })
    }

    send(message) {
        this.client.produce(this.buildMessage(message))
    }

    buildMessage(message) {
        return {
            messages:[{
                key: this.schemaRegistry.serialize({
                    data: 'k6-key-id-' + this.generateRandom(),
                    schemaType: SCHEMA_TYPE_STRING,
                }),
                value: this.schemaRegistry.serialize({
                    data: JSON.stringify(message),
                    schemaType: SCHEMA_TYPE_STRING
                })
            }]
        }
    }

    generateRandom(min = 0, max = 90000) {

        // find diff
        let difference = max - min

        // generate random number
        let rand = Math.random()

        // multiply with difference
        rand = Math.floor(rand * difference)

        // add with min value
        rand = rand + min

        return rand
    }
}
```

in terminal: ./k6 run scenarios/orderPaidScenario.js 
Output:
First time its okey producing, after 5 seconds i see more error messages:

```bash
ERRO[0011] Error writing messages., OriginalError: %!w(context.deadlineExceededError={})  error="Error writing messages., OriginalError: %!w(context.deadlineExceededError={})"
ERRO[0011] GoError: Error writing messages., OriginalError: %!w(context.deadlineExceededError={})
constantat github.com/mostafa/xk6-kafka.(*Kafka).writerClass.func1 (native)
        at send (file:///Users/WebstormProjects/k6-test/common/kafka/producer.js:24:46(7))
        at produce (file:///Users/WebstormProjects/k6-test/common/kafka/exchanges/baseExchange.js:9:27(5))
        at orderPaid (file:///Users/WebstormProjects/k6-test/common/kafka/exchanges/OrderPaidNotify.js:14:21(12))
        at file:///Users/WebstormProjects/k6-test/scenarios/orderPaidScenario.js:41:22(15)
```

**Comment by atlok** [comment]
Network is very heavily loaded after launch test with kafka writer
![image](https://user-images.githubusercontent.com/2855516/220591200-524942ea-1dc7-4bd4-8f06-5e9422c0370d.png)

**Comment by mostafa** [comment]
Hey @atlok,

Your `readTimeout` is in nanoseconds. Read more about it in question 10 of [FAQ](https://github.com/mostafa/xk6-kafka#faq).

**Comment by atlok** [comment]
Hi @mostafa with this option **readTimeout: 1000** i see in result response in terminal value is 1 second
![image](https://user-images.githubusercontent.com/2855516/220658742-e85413bf-d6f2-4e13-8c39-fe28275cd9c6.png)

**Comment by mostafa** [comment]
@atlok 

This looks like an error. Can you try to `SECOND` I suggested above?

**Comment by atlok** [comment]
I tried set readTimeout to 20000000 and i had same result.

Why does channel become very clogged with such small loads?

**Comment by mostafa** [comment]
@atlok 
Can you try setting `maxWait` to `1 * SECOND` or 2 seconds? Also, can you paste here the metrics you receive in the end of test summary?

**Comment by atlok** [comment]
Hi @mostafa 
Where placed param maxWait?

**Comment by mostafa** [comment]
Hey @atlok,

In the [`ReaderConfig`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/ReaderConfig.md).

**Comment by atlok** [comment]
I'm not use consumer(reader) in mine test, only producer (writer)

**Comment by mostafa** [comment]
@atlok Sorry, my bad.

Can you give me a list of metrics from your end-test summary?

**Comment by atlok** [comment]
![image](https://user-images.githubusercontent.com/2855516/221571424-c3daa1ca-e9db-4497-8563-b0d3db8f1c9d.png)

**Comment by mostafa** [comment]
Everything looks okay except the dropped iterations and that you're creating 100 iterations per each second, hence I suppose you're creating too many iterations. And the error you see could be due to the dropped iterations.

**Comment by atlok** [comment]
Experimentally, I came to conclusion that optimal value is 50 vue. However, we need much more.

**Comment by mostafa** [comment]
Can you create bigger batches instead?

**Comment by atlok** [comment]
New trable with kafka work
Amount tcp connection over hight
![image](https://user-images.githubusercontent.com/2855516/222186340-db443605-524a-42d9-85b5-8df08d348aad.png)

**Comment by narkq** [comment]
Apparently, the culprit was the [metadata polling machinery](https://github.com/segmentio/kafka-go/blob/294fbdbf43ce5c2bc6aa89d8a35db949e1f95367/transport.go#L601-L611) in kafka-go library.
Each few seconds it will fetch metadata from the kafka cluster with all topics, replicas, partitions, etc.
For our cluster that would be about 1MB each response.
Since each VU runs that loop independently, with 100+ VUs this will quickly saturate 100MB/s connection bandwidth, leading to all those weird timeouts.

As a stopgap measure I made a patch for kafka-go library, which makes it to query for metadata only once, cache the response in a global variable, and then use that response instead of polling from that point on (assuming that cluster topology does not change during test).

A better solution probably would be somehow allowing to query metadata only for topics that's needed for testing (not sure if kafka-go allows that, maybe I missed something).

**Comment by narkq** [comment]
> New trable with kafka work Amount tcp connection over hight ![image](https://user-images.githubusercontent.com/2855516/222186340-db443605-524a-42d9-85b5-8df08d348aad.png)

That was actually a bug in the initial version of my patch.

**Comment by mostafa** [comment]
I suppose this is resolved. So, I'll close this. Feel free to reopen it if the issue persists.
