### ISSUE TITLE
Typo in api-docs (interface: TLSConfig)

### ISSUE THREAD

**Issue by bertalan-radostyan** [mostafa/xk6-kafka#203]
There is a typo in: https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/TLSConfig.md

https://github.com/mostafa/xk6-kafka/blob/fc71c8b09d67a898481a9b640b7c5b89b37d3802/api-docs/docs/interfaces/TLSConfig.md?plain=1#L12

https://github.com/mostafa/xk6-kafka/blob/fc71c8b09d67a898481a9b640b7c5b89b37d3802/api-docs/docs/interfaces/TLSConfig.md?plain=1#L66-L68

**serverCertPem** should be **serverCaPem**.

**Comment by mostafa** [comment]
Hey @bertalan-radostyan,

thanks for spotting the typo 🙏. I'll fix it ASAP.

**Comment by mostafa** [comment]
Fixed. ✅ Thanks! 🙏
