### ISSUE TITLE
Question about dashboard

### ISSUE THREAD

**Issue by nj-apps** [mostafa/xk6-kafka#204]
Hello,
I plan to use k6-kafka. I know some k6 dashboard but not for the kafka extension. So before I start creating a new Grafana dashboard I was wondering if one already exists?
Thank you very much
kind regards

**Comment by mostafa** [comment]
Hey @nj-apps,

There is no dashboard that I know of. Feel free to create it and contribute it to [Grafana Dashboards](https://grafana.com/grafana/dashboards/) or here in this repository.

**Comment by nj-apps** [comment]
Thank you very much. I will share the dashboard once operational

**Comment by mostafa** [comment]
Feel free to re-open this when it's ready.

**Comment by vipul-mykaarma** [comment]
hi ,is there any dashboard available ?
