### ISSUE TITLE
filter out on reader.consume()

### ISSUE THREAD

**Issue by sarut0bi** [mostafa/xk6-kafka#205]
Hi ,
Is there any way to filter out data in reader consume (ex using a header ?) ...I cannot find out any option in documentation...
I cannot be sure to be the only producer in my topics & sometimes I get false negative in my checks when topic is been use by someone else; any idea how to avoid it?
Greets,

**Comment by mostafa** [comment]
@sarut0bi 

I am afraid you need to do it in JS. That is, loop over the results and filter them manually.

**Comment by mostafa** [comment]
@sarut0bi 

I suppose this is resolved. Feel free to reopen it if the issue persists.
