### ISSUE TITLE
Avro message deserialization error

### ISSUE THREAD

**Issue by takdan01** [mostafa/xk6-kafka#210]
I tried to deserialize the Avro message and I got back this error:
ERRO[0011] a panic occurred during JS execution: runtime error: invalid memory address or nil pointer dereference.

**Comment by mostafa** [comment]
Hey @takdan01,

Please provide me with an example script, as I won't be able to reproduce this based on this log message.

**Comment by takdan01** [comment]
Hello @mostafa,

I would like to get the Avro schema from schema-registry and deserialize the Kafka message with Avro schema. 

`import {
    Reader,
    Connection,
    SchemaRegistry,
    SCHEMA_TYPE_AVRO,
} from "k6/x/kafka";

export function deserialization(message){
    const schemaRegistry = new SchemaRegistry({
        url: KAFKA.SCHEMA_REGISTRY_URL
    });
    if(typeof(message) != "undefined" ){
        let deserializedValue = schemaRegistry.deserialize({
            data: message,
            schemaType: SCHEMA_TYPE_AVRO,
        });
        return deserializedValue;
    }
    else {
        return null
    }
        
}`

**Comment by mostafa** [comment]
@takdan01 

You are not passing the `schema` to `deserialize` method, which is why it is not working. Please have a look at this [example script](https://github.com/mostafa/xk6-kafka/blob/main/scripts/test_avro_with_schema_registry.js) and use the [`getSchema`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/classes/SchemaRegistry.md#getschema) method to get the schema from Schema Registry.

**Comment by takdan01** [comment]
I wrote this small code what it tries to get schema from Schema Registry and I got same error what mentioned before.
`ERRO[0010] panic: runtime error: invalid memory address or nil pointer dereference`

`export function getSchema(schemaSubject){
    console.log(schemaSubject)
    let valueSchema = schemaRegistry.getSchema(schemaSubject);
    console.log(valueSchema);
    return valueSchema;
}`

**Comment by mostafa** [comment]
Try this instead:

```javascript
export function getValueSchema(schemaSubject){
    console.log(schemaSubject)
    // 0 means the latest version of the schema.
    let valueSchema = schemaRegistry.getSchema({version: 0, subject: schemaSubject});
    console.log(valueSchema);
    return valueSchema;
}
```

**Comment by takdan01** [comment]
Thanks your help. Now the code is working.
