### ISSUE TITLE
How can one read the last x messages from a topic with a reader?

### ISSUE THREAD

**Issue by Bogdan405** [mostafa/xk6-kafka#213]

**Comment by Bogdan405** [comment]
Thank you, can I set the offset to the latest message somehow? Or is there a way to get the current offset without consuming all the messages?

**Comment by mostafa** [comment]
@Bogdan405 
There is currently no explicit way to do it, unless you read a single message (`limit=1`).

**Comment by Bogdan405** [comment]
Ok, I will keep experimenting

**Comment by mostafa** [comment]
I'll close this issue, and feel free to re-open it if the issue is not resolved.

**Comment by Manuel-Moya** [comment]
@Bogdan405 , how did you solve your requirement? I am trying to get the last message as well.
