### ISSUE TITLE
Difference between outputted metrics order: read>wait vs wait>write

### ISSUE THREAD

**Issue by Bogdan405** [mostafa/xk6-kafka#214]
Hello, I noticed that when outputting metrics for reader, kafka-reader-**read**-seconds comes above kafka-reader-**wait**-seconds in the list, but for writer, kafka-writer-**wait**-seconds is above kafka-writer-**write**-seconds

Is there a reason they are ordered this way?

**Comment by mostafa** [comment]
Hey @Bogdan405,

I don't see any issues with this 🤔, as k6 takes care of the [metrics](https://k6.io/docs/using-k6/metrics/). Unless I am missing something.

**Comment by Bogdan405** [comment]
Thanks was just wandering if there is a rule.
