### ISSUE TITLE
Effect of partition count is not reflecting on publishing throughput/ speed/ time while testing using xk6-kafka

### ISSUE THREAD

**Issue by satyaDcoder** [mostafa/xk6-kafka#219]
We are tuning following  parameter mentioned in https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/WriterConfig.md

batchBytes
batchSize
batchTimeout
compression

Problem Statement: 

We publishing 500,000 of message (message size 8KB)in the topic, by varying the partition count (1 to 18) and collecting the publishing time and  throughput (Speed) for each partition.
For each partition it is taking almost same time. 

why publishing throughout / time is same for different partition count?

In general publishing throughput  increases as we increase partition count.

Code Snippet: https://github.com/mostafa/xk6-kafka/blob/main/scripts/test_sasl_auth.js

<img width="1741" alt="Screenshot 2023-05-16 at 3 03 44 PM" src="https://github.com/mostafa/xk6-kafka/assets/15271949/10001097-da13-4678-a200-656ed4e6e21e">

Can you please let me know why effect of partition count is not reflecting  on publishing throughput / speed/ time while testing using xk6-kafka?

**Comment by mostafa** [comment]
Hey @satyaDcoder,

Increasing the `batchSize` and `batchBytes` increases the amount of time kafka-go waits to queue a batch of messages and send it. That is the value of these variables are reversely proportional to the amount of time it takes to flush messages to Kafka.

That being said, have you tried [setting the partition in the message](https://github.com/mostafa/xk6-kafka/blob/62c45f10837021a2b0b1ca6ffb84e4184d7cfaf6/scripts/test_json.js#L87) to avoid Kafka to choose a partition for you?

**Comment by mostafa** [comment]
@satyaDcoder 

I suppose this is resolved. Feel free to reopen it if the issue persists.
