### ISSUE TITLE
Schema gets updated with every message produce

### ISSUE THREAD

**Issue by saad1200** [mostafa/xk6-kafka#22]
I have notices an issue with produce with configuration with schema and schema serializer. For some reason the defaults (which can be null) are removed from from the server schema as soon as I run the tests. 
It seems the goavro lib that is being used does this as part of serialization. The problem is, this schema later is used as in a post request to fitch the schema id from the server. This post request update the server schema in this case. I could not find a way that we provide the schema id to bypass this logic/behavior.

**Comment by ssam5532** [comment]
Any update on this?

**Comment by mostafa** [comment]
Hey @saad1200 @ssam5532!

Can any of you provide an example script (and/or configuration) you use, so I can test it?

**Comment by saad1200** [comment]
@mostafa Any produce code example from the repo can be used to reproduce this. It has been few months now, but I think it is an issue with goavro lib.

we noticed that xk6-kafka is posting a new schema when called with produceWithConfiguration. Looks like  it’s because they’re stripping out some of the java specific types and before posting the schema to the registry (which I guess they need to do, to get an ID).
https://github.com/mostafa/xk6-kafka/blob/57dfc78d0b9c85557519772c3bce7e5f17ed3b30/schemaRegistry.go#L59

If you look at line 54 and 56,  goavro’s codec is turning the schema into and object, then making it into a string again on line 56.

**Comment by saad1200** [comment]
@ssam5532 our work around is to setup wiremock and use it as schema registry proxy. It is another dependency and far from ideal solution but allowed us to continue using K6.

**Comment by mostafa** [comment]
@saad1200
I suppose this can be fixed by trying to fetch the schema first before trying to post one. We can also use something like [srclient](https://github.com/riferrei/srclient) and have it handle everything, but it's an extra dependency for just two HTTP requests.

**Comment by mostafa** [comment]
@saad1200 @ssam5532 I'd be happy to have your feedback on #52.

**Comment by mostafa** [comment]
@saad1200 @ssam5532 
The PR (#52) is merged now, and you can test it to see if it fixes the issue or not. I haven't released a version yet, so you need to build the latest `main` according to xk6 build instructions to test it. Let me know if you face any issues along the way!
Also, based on my tests, the schema doesn't get updated.

**Comment by saad1200** [comment]
@mostafa sorry for the delay. I will block some time next weekend to test the changes.

**Comment by kusumkappdirect** [comment]
@saad1200  , can you please help me here. , my schema also get updated with each sent message on topic , how you retrieve the schema first and then send same ?

**Comment by saad1200** [comment]
@kusumkappdirect
If you are using latest release and still having this issue all you need to do is to setup wiremock on the dev server or locally, then in the k6 setup method get the schema from the schema registry and stub the methods to return that schema using wiremock. Pass wiremock address instead of the schema registry to the k6 extension produce method.
I will charge my code with you soon
