### ISSUE TITLE
does xk6-kafka support avro union type?

### ISSUE THREAD

**Issue by luciowu** [mostafa/xk6-kafka#220]
Hello,

I am trying to use xk6-kafka with Avro format.
It is fine for me to use this example https://github.com/mostafa/xk6-kafka/blob/main/scripts/test_avro_no_schema_registry.js

But if I did a small modification on the code  with avro union type (because in our case, we use union type) as the following

```
const valueSchema = JSON.stringify({
  type: "record",
  name: "Value",
  namespace: "dev.mostafa.xk6.kafka",
  fields: [
    {
      name: "name",
      type : ["null", "string"],
      default: null
    },
  ],
});
```
```

export default function () {
  for (let index = 0; index < 2; index++) {
    let messages = [
      {
        value: schemaRegistry.serialize({
          data: {
            name: "xk6-kafka",
          },
          schema: { schema: valueSchema },
          schemaType: SCHEMA_TYPE_AVRO,
        }),
      },
    ];

    writer.produce({ messages: messages });
  }
```

it will report error
`executor=constant-vus scenario=sasl_auth source=stacktrace
ERRO[0005] GoError: Failed to encode data, OriginalError: %!w(*errors.errorString=&{cannot decode textual record "dev.mostafa.xk6.kafka.Value": cannot decode textual union: expected: '{'; actual: '"' for key: "name"})`

Not sure is this issue related to my code or this plugin. Could you help on it? 
Thanks.

**Comment by mostafa** [comment]
Hey @luciowu,

I use [srclient](https://github.com/riferrei/srclient) for management of schema and schema registry, which internally uses [go-avro](https://github.com/go-avro/avro). As far as I've looked, go-avro supports [union types](https://github.com/go-avro/avro/blob/master/examples/generic_datum/generic_datum.go#L52-L67). I tried to fix your script, but it seems something is lost in translation between `JSON.stringify`, Goja runtime and `avro.NativeFromTextual`. And it looks like a bug.

**Comment by luciowu** [comment]
Yep. you're right. I just figure out the difference in the go-avro and other programming language libraries.
Now it works.
Thank you very much.
