### ISSUE TITLE
how can we know the topic details(current offset etc) of a particular topic?

### ISSUE THREAD

**Issue by arpitaso** [mostafa/xk6-kafka#226]
@mostafa 
I have set the below offset and 
let offset = 0;
but the topic always reads data from 0th offset, in our use case we want to consume data from current offset.
Is there any way to do so?

**Comment by mostafa** [comment]
@arpitaso 

You can pass the start `offset` by populating it in the [`ReaderConfig`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/ReaderConfig.md).

**Comment by mostafa** [comment]
@arpitaso 

I suppose this is resolved. Feel free to reopen it if the issue persists.

**Comment by arpitaso** [comment]
@mostafa 
i tried the above
```
import {
    Writer,
    Reader,
    Connection,
    SchemaRegistry,
    SCHEMA_TYPE_JSON,
    SASL_SCRAM_SHA512, START_OFFSETS
} from "k6/x/kafka";

  reader = new Reader({
        brokers: brokers,
        topic: topic,
        partition: partition,
        offset: START_OFFSETS.START_OFFSETS_LAST_OFFSET,
        sasl: saslConfig,
        tls: tlsConfig,
    });
    
```
    
    
    but it gives the below error
```
    ERRO[0002] TypeError: Cannot read property 'START_OFFSETS_LAST_OFFSET' of undefined
running at file:///Users/arpita.sood/Documents/Maersk_code/sre-perf-ls-test-demo/dev_latest/dev-test.js:96:30(56)  executor=shared-iterations scenario=default source=stacktrace
```

**Comment by mostafa** [comment]
@arpitaso 
import `START_OFFSETS_LAST_OFFSET` directly.

**Comment by shreya-haridas** [comment]
@arpitaso 
it actually should be startOffset: LAST_OFFSET

see https://github.com/mostafa/xk6-kafka/issues/281 for more clarity

**Comment by mikooor** [comment]
Hi, 
I actually still have issues reading from latest offset from particular topic and partition. Is there any possibility to properly document and confirm what is the correct way to use START_OFFSETS_LAST_OFFSET or LAST_OFFSET? 
Thanx a lot.
Miro
