### ISSUE TITLE
Request to add authentication through oauth bearer token

### ISSUE THREAD

**Issue by PrabhanjanDesai** [mostafa/xk6-kafka#228]
We need authenticate to kafka using bearer token. Since we are using xk6 , we need this authentication to be added to xk6-kafka extension. Please do the needful.

**Comment by mostafa** [comment]
@PrabhanjanDesai 

xk6-kafka uses the [kafka-go](https://github.com/segmentio/kafka-go) library and it doesn't support OAuth Bearer Token authentication yet:
- https://github.com/segmentio/kafka-go/issues/539
- https://github.com/segmentio/kafka-go/issues/238
