### ISSUE TITLE
Unable to use relative path for the below script for parameters clientCertPem, clientKeyPem, serverCaPem

### ISSUE THREAD

**Issue by arpitaso** [mostafa/xk6-kafka#231]
@mostafa I am using the below script my k6 extension is in documents folder and inside documents folder i have a folder test_folder which has script.js and 3 pem files, but when i run the script from documents folder,  the script.js has clientCertPem, clientKeyPem, serverCaPem these 3 are taking relative path and i get an error as shown below.
Can you please help here?

import { check } from "k6";
import {
    Writer,
    Reader,
    Connection,
    SchemaRegistry,
    SCHEMA_TYPE_JSON,
    TLS_1_2,
    SASL_SCRAM_SHA512
} from "k6/x/kafka"; // import kafka extension

export const options = {
    stages: [
      { target: 1, duration: '30s' },
      { target: 3, duration: '30s' },
      { target: 1, duration: '30s' }
    ],
  };

const brokers = [""];
const topic = "";

// SASL config is optional
const saslConfig = {
    username: "",
    password: "",
    // Possible values for the algorithm is:
    // NONE (default)
    // SASL_PLAIN
    // SASL_SCRAM_SHA256
    // SASL_SCRAM_SHA512
    // SASL_SSL (must enable TLS)
    // SASL_AWS_IAM (configurable via env or AWS IAM config files - no username/password needed)
    algorithm: SASL_SCRAM_SHA512
};

// TLS config is optional
const tlsConfig = {
    enableTls: true,
    insecureSkipTlsVerify: true,
    minVersion: TLS_1_2,

    // Only needed if you have a custom or self-signed certificate and keys
    clientCertPem: "./client-cert-0.pem",
    clientKeyPem: "./client-key.pem",
    serverCaPem: "./server-ca.pem",
};

let offset = 0;
// partition and groupId are mutually exclusive
let partition = 0;
let numPartitions = 1;
let replicationFactor = 1;

const writer = new Writer({
    brokers: brokers,
    topic: topic,
    sasl: saslConfig,
    partition: partition,
    tls: tlsConfig,
});
const reader = new Reader({
    brokers: brokers,
    topic: topic,
    partition: partition,
    offset: offset,
    sasl: saslConfig,
    tls: tlsConfig,
});
const connection = new Connection({
    address: brokers[0],
    sasl: saslConfig,
    tls: tlsConfig,
});
const schemaRegistry = new SchemaRegistry();

export default function () {
    // for (let index = 0; index < 100; index++) {
        let messages = [
            {
                key: schemaRegistry.serialize({
                    data: {
                        correlationId: "test-id-abc-" + 1,
                    },
                    schemaType: SCHEMA_TYPE_JSON,
                }),
                value: schemaRegistry.serialize({
                    data: {

                        "templateId": 5,
                        "testId": 4,
                        "status": "deactive",
                        "message": "Hi, i am testing "
                    },
                    schemaType: SCHEMA_TYPE_JSON,
                }),
            },
        ];
        writer.produce({ messages: messages });
    // }

    // Read 10 messages only

    // let messages = reader.consume({ limit: 10 });
    // console.log("---------_>>>>>",messages.length)
    let mesg = reader.consume({ limit: 10 });
        console.log("correlation=====>>>", schemaRegistry
        .deserialize({ data: mesg[0].key, schemaType: SCHEMA_TYPE_JSON })
        .correlationId);

        console.log("schema------>>>>>", schemaRegistry.deserialize({
        data: messages[0].value,
        schemaType: SCHEMA_TYPE_JSON,
        }));

}

export function teardown(data) {
    writer.close();
    reader.close();
    connection.close();
}

error 

DEBU[0000] Babel: Transformed                            t=75.896ms
ERRO[0000] Cannot process TLS config                     error="File not found: ./client-cert-0.pem, OriginalError: %!w(*fs.PathError=&{stat ./client-cert-0.pem 2})"
ERRO[0000] Cannot process TLS config                     error="File not found: ./client-cert-0.pem, OriginalError: %!w(*fs.PathError=&{stat ./client-cert-0.pem 2})"
ERRO[0000] Cannot process TLS config                     error="File not found: ./client-cert-0.pem, OriginalError: %!w(*fs.PathError=&{stat ./client-cert-0.pem 2})"

**Comment by mostafa** [comment]
Hey @arpitaso,

Have you tried `./tests_folder/...`? Or the absolute path?

**Comment by arpitaso** [comment]
@mostafa ./tests_folder/...

**Comment by mostafa** [comment]
@arpitaso Is it fixed?

**Comment by arpitaso** [comment]
yes
