### ISSUE TITLE
Does xk6 support to get secrets from azure keyvault

### ISSUE THREAD

**Issue by arpitaso** [mostafa/xk6-kafka#234]
Hi @mostafa 
Below is the script. I want to get secrets from azure keyvault, does xk6 lets us do that??

const saslConfig = {
             username: "username",
             password: "password",
             algorithm: SASL_SCRAM_SHA512,
 };

**Comment by mostafa** [comment]
@arpitaso 

kafka-go supports AWS IAM only.
