### ISSUE TITLE
ERRO[0002] GoError: Failed to decode JKS file: /test/833/truststore.jks, OriginalError: %!w(*errors.errorString=&{got invalid magic})  running at github.com/grafana/xk6-kafka.(*Kafka).loadJKSFunction-fm (native)

### ISSUE THREAD

**Issue by arpitaso** [mostafa/xk6-kafka#236]
@mostafa 
I am getting an error while running the xk6 script. Below is the script and the error.
Please help here.
Thanks 

```
import {
    LoadJKS,
    TLS_1_2
} from "k6/x/kafka";
import {
    Writer,
    Reader,
    Connection,
    SchemaRegistry,
    SCHEMA_TYPE_JSON,
    SASL_SCRAM_SHA512
} from "k6/x/kafka";
import VaultManager from './VaultManager.js';

export let options = {
    stages: [{
            target: 1,
            duration: '30s'
        }
    ],
};

export const vault = new VaultManager(' Platform', 'DEV');

let offset = -1;
// partition and groupId are mutually exclusive
let partition = 0;
let numPartitions = 1;
let replicationFactor = 1;

let username = "";
let password = "";
let passwordToAccessTrustore = "";
let saslConfig = {};

let writer;
let reader;
let connection;


export function setup() {
    console.log('Inside setup function ');
    username = vault.getSecretFromVault("USERNAME");
    password = vault.getSecretFromVault("PASSWORD");
    passwordToAccessTrustore = vault.getSecretFromVault("PASSWORD-JKS");
}

export function initializeCredentials() {
    console.log('Inside initializeCredentials function');
    if (!username || !password || !passwordToAccessTrustore) {
        username = vault.getSecretFromVault("USERNAME");
        password = vault.getSecretFromVault("PASSWORD");
        passwordToAccessTrustore = vault.getSecretFromVault("PASSWORD-JKS");

        saslConfig = {
            username: username,
            password: password,
            algorithm: SASL_SCRAM_SHA512
        };
        console.log('saslConfig = ' + saslConfig);
    }
}

const trustStoreUrl = vault.getIPaceEnvConfig().getValueFromEnvFor('ROOTDIR')+'/truststore.jks';
console.log('trustStoreUrl ==' + trustStoreUrl)

export default function(data) {
    initializeCredentials();

    const jks = LoadJKS({
        path: trustStoreUrl,
        password: passwordToAccessTrustore,
        clientCertAlias: "kafka",
        clientKeyAlias: "kafka",
        clientKeyPassword: passwordToAccessTrustore,
        serverCaAlias: "server",
    });

    const tlsConfig = {
        enableTls: true,
        insecureSkipTlsVerify: true,
        minVersion: TLS_1_2,
        clientCertPem: jks["clientCertsPem"][0], // The first certificate in the chain
        clientKeyPem: jks["clientKeyPem"],
        serverCaPem: jks["serverCaPem"],
    };

    const brokers = ["digital.net:443"];
    const topic = "internal.any.v1";

    const schemaRegistry = new SchemaRegistry();

    writer = new Writer({
        brokers: brokers,
        topic: topic,
        sasl: saslConfig,
        partition: partition,
        tls: tlsConfig,
    });

    reader = new Reader({
        brokers: brokers,
        topic: topic,
        partition: partition,
        offset: offset,
        sasl: saslConfig,
        tls: tlsConfig,
    });

    connection = new Connection({
        address: brokers[0],
        sasl: saslConfig,
        tls: tlsConfig,
    });
    let messages = [{
        key: schemaRegistry.serialize({
            data: {
                correlationId: "test-id-abc-" + 1,
            },
            schemaType: SCHEMA_TYPE_JSON,
        }),
        value: schemaRegistry.serialize({
            data: {
                templateId: 5,
                testId: 4,
                status: "deactive",
                message: "Hi, I am testing",
            },
            schemaType: SCHEMA_TYPE_JSON,
        }),
    }];

    writer.produce({
        messages: messages,
    });

    let mesg = reader.consume({
        limit: 10,
    });

    console.log("correlation=====>>>", schemaRegistry.deserialize({
        data: mesg[0].key,
        schemaType: SCHEMA_TYPE_JSON,
    }).correlationId);

    console.log("schema------>>>>>", schemaRegistry.deserialize({
        data: messages[0].value,
        schemaType: SCHEMA_TYPE_JSON,
    }));
}

export function teardown() {
    if (writer) writer.close();
    if (reader) reader.close();
    if (connection) connection.close();
}
```

error 
`ERRO[0002] GoError: Failed to decode JKS file: /test/833/truststore.jks, OriginalError: %!w(*errors.errorString=&{got invalid magic})

running at github.com/grafana/xk6-kafka.(*Kafka).loadJKSFunction-fm (native)`

**Comment by mostafa** [comment]
@arpitaso 

There are two reasons I can think of:
1. You are using a PKCS#12-encoded keystore or some other supported format, which is not supported by [keystore-go](https://github.com/pavlo-v-chernykh/keystore-go) and hence xk6-kafka.
2. Your file is corrupt.

**Comment by arpitaso** [comment]
> @arpitaso
> 
> There are two reasons I can think of:
> 
> 1. You are using a PKCS#12-encoded keystore or some other supported format, which is [not supported](https://github.com/pavlo-v-chernykh/keystore-go/blob/e49ca8fe83f475c1bed972a54cb1e9a396dfa888/keystore.go#L172-L174) by [keystore-go](https://github.com/pavlo-v-chernykh/keystore-go) and hence xk6-kafka.
> 2. Your file is corrupt.

@mostafa  the same script and files are working as expected in my local, but giving the above error in dev env

**Comment by mostafa** [comment]
In which dev env? Are you using the same exact version of xk6-kafka? Can you run `k6 version` to see the build info?

**Comment by arpitaso** [comment]
@mostafa 
my local has
arpita.sood@MMDVD9TJQR30M ~ % k6 version
k6 v0.45.0 ((devel), go1.20.5, darwin/arm64)

dev env has / # k6 version
k6 v0.44.1 ((devel), go1.20.5, linux/amd64)

**Comment by mostafa** [comment]
@arpitaso 

You are using an older version of k6 on dev env. Also, you didn't list the plugin version info.

**Comment by arpitaso** [comment]
@mostafa how to list the plugin version info?

**Comment by arpitaso** [comment]
@mostafa 
local
arpita.sood@MMDVD9TJQR30M ~ % ./k6 version
k6 v0.44.1 ((devel), go1.20.5, darwin/arm64)
Extensions:
  github.com/mostafa/xk6-kafka v0.18.1, k6/x/kafka [js]
  
  dev
  / # k6 version
k6 v0.44.1 ((devel), go1.20.5, linux/amd64)
Extensions:
  github.com/grafana/xk6-kafka (devel), k6/x/kafka [js]

**Comment by arpitaso** [comment]
@mostafa i will use the same version for xk6 and k6 that i am using in local.
will update once i have done this, if issue persists

**Comment by arpitaso** [comment]
@mostafa 
the configuration for k6 and xk6 in dev and local is below

local
arpita.sood@MMDVD9TJQR30M ~ % k6 version
k6 v0.45.0 ((devel), go1.20.5, darwin/arm64)

arpita.sood@MMDVD9TJQR30M ~ % ./k6 version
k6 v0.44.1 ((devel), go1.20.5, darwin/arm64)
Extensions:
  github.com/mostafa/xk6-kafka v0.18.1, k6/x/kafka [js]

------------------------------------------------------------------

dev
/ # k6 version
k6 v0.44.1 ((devel), go1.20.5, linux/amd64)
Extensions:
  github.com/grafana/xk6-kafka (devel), k6/x/kafka [js]
  
  i see in my local i have extension as  github.com/mostafa/xk6-kafka v0.18.1, k6/x/kafka [js] but in dev the extension is   github.com/grafana/xk6-kafka (devel), k6/x/kafka [js]
 1. could this be the reason behind the script not running in dev?
 2. do i have to use the same extension (  github.com/mostafa/xk6-kafka v0.18.1, k6/x/kafka [js]
) that i am using in local and replace the  extension( github.com/grafana/xk6-kafka (devel), k6/x/kafka [js]) in dev?

**Comment by mostafa** [comment]
@arpitaso 

Try running xk6 without pointing to a local copy. This will fetch the latest version from GitHub and build k6 with that. FYI, the latest version of xk6-kafka is v0.1.9.0 and k6 is v0.45.0.
```bash
xk6 build --with github.com/mostafa/xk6-kafka@latest
```

**Comment by arpitaso** [comment]
@mostafa 
in my local below is the version for k6 and ./k6 
```
arpita.sood@MMDVD9TJQR30M sre-perf-ls-test-demo % k6 version
k6 v0.45.0 ((devel), go1.20.5, darwin/arm64)

arpita.sood@MMDVD9TJQR30M sre-perf-ls-test-demo % ./k6 version
k6 v0.45.0 ((devel), go1.20.5, darwin/arm64)
Extensions:
  github.com/mostafa/xk6-kafka v0.19.0, k6/x/kafka [js]
```
  the script with above config is working as expected


in dev env k6 and ./k6 version is below
```
k6 version
k6 v0.45.0 ((devel), go1.20.6 linux/amd64)
Extensions:
  github.com/mostafa/xk6-kafka (devel), k6/x/kafka [js]

 ./k6 version
k6 v0.45.0 ((devel), go1.20.6, linux/amd64)
Extensions:
  github.com/mostafa/xk6-kafka (devel), k6/x/kafka [js]
```
even though whatever version i use in the dev env, i get (devel) in the extension but all versions are working as expected in local env.

please help here,
thanks

**Comment by mostafa** [comment]
@arpitaso 

That's actually a k6 question that should be posted on <https://community.k6.io>. Nevertheless, you are using a compiled version of k6 in your `$PATH` and your local directory. Either way, I _highly recommend_ using the latest Docker images or binaries from [here](https://github.com/mostafa/xk6-kafka#download-binaries).

**Comment by mostafa** [comment]
@arpitaso 

I suppose this is resolved, so I'll close it.

**Comment by arpitaso** [comment]
@mostafa i am using the same ./k6 version in dev, and have the docker image also the way it is mentioned in this doc.
still i get this error
