### ISSUE TITLE
is there any support of providing the Authentication to producer using SSL certificate (e.g. keystore or truststore certs)?

### ISSUE THREAD

**Issue by sumit-ps** [mostafa/xk6-kafka#24]

**Comment by mostafa** [comment]
Hey @sumit-ps,

there's no support for that yet, but I'd be happy to review any contributions.

**Comment by sumit-ps** [comment]
@mostafa thanks for your quick response, i'll go through it and will update you if i found any solution. 
could you please also confirm, can we provide the TLS configuration for authentication to the producer, i was going through the issues and found that there is PR merged regarding the TLS config?

**Comment by mostafa** [comment]
There's support for TLS on reader and writer, as stated in [kafka-go README](https://github.com/segmentio/kafka-go#tls-support). And it seems to be pretty straightforward, as I found out in this [example](https://github.com/denji/golang-tls) and the Go docs' [TLS example test](https://golang.org/src/crypto/tls/example_test.go).

**Comment by mostafa** [comment]
Added in #31.

**Comment by mostafa** [comment]
Added in #31.
