### ISSUE TITLE
Writer is not sending to the indicated partition

### ISSUE THREAD

**Issue by hernanmateika-stuart** [mostafa/xk6-kafka#247]
Hi! 
Question, does the partition feature on writer works? 
It doesn't matter to what partition you tell the message object, it always distributes messages equally. Maybe this feature is not working as it should?

code example that we use to send messages:

```

		this.writer.produce({
		messages: [
		{
				key: this.schemaRegistry.serialize({
				data: message.keyData,
				schemaType: SCHEMA_TYPE_JSON,
				}),
				value: this.schemaRegistry.serialize({
						data: message.valueData,
						schemaType: SCHEMA_TYPE_JSON,
				}),
				headers: message.headers,
				offset: index,
				partition: 0,
				time: new Date(),
		},
		],
		});
```

**Comment by mostafa** [comment]
Hey @hernanmateika-stuart,

As indicated [here](https://github.com/segmentio/kafka-go/blob/f4ca0b48296538eb5639027cd83f40a3828caf7d/message.go#L15) and subsequently [here](https://github.com/mostafa/xk6-kafka/blob/aae567b993044cebe3e7b695a3dd15ebe0785349/writer.go#L58), you cannot neither set the partition on individual messages nor on the writer config itself. Either your topic has a single partition, or kafka-go decides on which partition the message should end up using a balancer, as mentioned [here](https://github.com/segmentio/kafka-go/blob/f4ca0b48296538eb5639027cd83f40a3828caf7d/writer.go#L16-L22). Currently five [balancers](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/enums/BALANCERS.md) are supported on the [WriterConfig](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/WriterConfig.md#balancer).

**Comment by hernanmateika-stuart** [comment]
Thanks for the clarification @mostafa, seeing the partition in the example scripts has given me confusion that it could be used for this.
Thanks again, I'm okay with closing the issue!

**Comment by mostafa** [comment]
Hey,

I suppose your question is answered, I'll close this issue. If you have further questions related to the same issue, please re-open this, otherwise open a new one.
