### ISSUE TITLE
Consumer waits 10 minutes when no message are coming

### ISSUE THREAD

**Issue by Bewi42** [mostafa/xk6-kafka#26]
Hello,
I run a script where I produce a message to a topic A then waits for another message on a topic B.
Sometimes, message is not posted on topic B, and I would like the consumer to wait a few seconds, no more. Currently, it waits around 10 minutes.
I don't really understand why as I see that the MaxWait is configured to 200ms in the go consumer class.

**Comment by mostafa** [comment]
I tried to run a simple test with no parameters to k6 (a simple `./k6 run test_json.js`) on a empty Kafka topic and it resulted in k6 setting the duration to 10m30s. This causes the script to iterate for 10 minutes and leave 30 seconds for a graceful stop. If there are no message in these 10m30s, it will report an error: `There was an error fetching messages: context deadline exceeded`.
So, I reduced the duration to 5 seconds to test again and this is the result and the intended behavior of k6 and xk6-kafka.

If you have any other questions or want to provide more information (test script, parameters, ...), let me know and I'll investigate.

```bash
$ ./k6 run -d 5s scripts/test_json.js

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: scripts/test_json.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 35s max duration (incl. graceful stop):
           * default: 1 looping VUs for 5s (gracefulStop: 30s)

There was an error fetching messages: context deadline exceeded
running (35.0s), 0/1 VUs, 0 complete and 1 interrupted iterations
default ✓ [======================================] 1 VUs  5s
WARN[0035] No script iterations finished, consider making the test duration longer

     ✓ is sent

     █ teardown

     checks.........................: 100.00% ✓ 100      ✗ 0
     data_received..................: 0 B     0 B/s
     data_sent......................: 0 B     0 B/s
     iteration_duration.............: avg=69.79µs min=69.79µs med=69.79µs max=69.79µs p(90)=69.79µs p(95)=69.79µs
     kafka.writer.dial.count........: 3       0.08568/s
     kafka.writer.error.count.......: 0       0/s
     kafka.writer.message.bytes.....: 44 kB   1.2 kB/s
     kafka.writer.message.count.....: 200     5.711978/s
     kafka.writer.rebalance.count...: 0       0/s
     kafka.writer.write.count.......: 200     5.711978/s
     vus............................: 1       min=1      max=1
     vus_max........................: 1       min=1      max=1
```

**Comment by Bewi42** [comment]
Hello,

Thanks for your answer, I have ran with a duration of 5s and it behaved like you said.
I'd like to reduce the graceful stop duration though, so I'll dig inside k6 options.

Thanks again.
