### ISSUE TITLE
Reader reads empty events

### ISSUE THREAD

**Issue by rhasanoff** [mostafa/xk6-kafka#261]
Hello,
When I create an event with my microservice in kafka xk6-kafka reader reads 2 events. One of them is normal event that I created another one is empty event. I checked in kafka UI and saw that events are generated with 2 offset apart. Kafka UI and kafka-console-consumer don't show these empty events only xk6-kafka reader can read them. I suspect these can be controlbatch events and that's why I have these missing offsets. Is there any way I can configure reader to skip and not read these empty events( like kafka-console-consumer doesn't read them I want the same behavior)?

**Comment by rhasanoff** [comment]
Hello @mostafa ,
I think the issue here is faulty check in reader.go isolation level handling.
`isolationLevel := IsolationLevels[isolationLevelReadUncommitted]
	if readerConfig.IsolationLevel == "" {
		isolationLevel = IsolationLevels[readerConfig.IsolationLevel]
	}`
Here isolationLevel will always be ReadUncommitted.

**Comment by mostafa** [comment]
@rhasanoff 

You are right! I am gonna fix it and release a new version now.

**Comment by mostafa** [comment]
Thanks for reporting the issue and finding the culprit. It is fixed in https://github.com/mostafa/xk6-kafka/commit/daf84e73d227e9738e6f2e6a31c1afb06bf71285 and released in [v0.21.1](https://github.com/mostafa/xk6-kafka/releases/tag/v0.21.1).
