### ISSUE TITLE
SASL_SSL and oauth authentication

### ISSUE THREAD

**Issue by Shawcs** [mostafa/xk6-kafka#262]
Hi there, I'm trying to use K6 to make different test on my kafka infrastructure, but as always, I'm facing some problems with the security. We only have SASL_SSL end point available and this authentication is made via a JWT token exchange with an ADFS.

To illustrate it, in java this is how clients are setup to authenticate to the cluster:
```
      sasl.login.callback.handler.class: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      sasl.jaas.config: >
              org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
              oauth.client.id="my-client-id" 
              oauth.client.secret="my-secret" 
              oauth.token.endpoint.uri="https://login/adfs/oauth2/token" ;
```
I'm not a GO/JS expert and so I'm having trouble to find how to setup that with your extension. Any help on that ?

Thanks

**Comment by mostafa** [comment]
Hey @Shawcs,

AFAIK this extension doesn't support OAuth, as I already mentioned in this https://github.com/mostafa/xk6-kafka/issues/228#issuecomment-1602579147.
