### ISSUE TITLE
How to set reader commit interval ?

### ISSUE THREAD

**Issue by CheViana** [mostafa/xk6-kafka#267]
Hello 
I am trying to pass in explicit values for commit interval and heartbeat interval for the `Reader`. However I noticed that those fields are of Go type `time.Duration` which is not JSON serializable (in Go v1 at least). I also noticed that `maxWait` field is of other type, custom struct, called just `Duration`, which has code to unmarshal it from JSON string https://github.com/mostafa/xk6-kafka/blob/main/reader.go#L64 . So my question is, how to pass value for commit interval correctly, for example 0.5 second? Does this param need to be also of type `Duration` like the `maxWait` is (e.g. pull request is needed)?

**Comment by mostafa** [comment]
Hey @CheViana,

I've answered this in the [FAQ](https://github.com/mostafa/xk6-kafka#faq) No. 10. At some point all the `time.Duration` fields should be converted to the custom `Duration` field, so that we can specify the duration as string, like `1s`.

**Comment by mostafa** [comment]
Hey @CheViana,

This is fantastic. I read it and found it very informative. Plus, the `topic` in the `ReaderConfig` is only used if you are not consuming from a group, as in `topic` and `groupTopics` are [mutually exclusive](https://github.com/mostafa/xk6-kafka/blob/5612337c573cfd0c915a9c6f0554b73fba3a72fa/reader.go#L190-L192).
