### ISSUE TITLE
Adding support for K6 0.49.0

### ISSUE THREAD

**Issue by ameetpal** [mostafa/xk6-kafka#275]
Hi, 

We are trying to upgrade to k6 0.49.0 but xk6 Kafka is currently using 0.48.0. Can we upgrade to 0.49.0 or I can raise a PR myself ?

**Comment by mostafa** [comment]
@ameetpal 
I'll upgrade ASAP.

**Comment by ameetpal** [comment]
Will you create a separate tag for this ?

**Comment by mostafa** [comment]
@ameetpal It is released as [v0.23.0](https://github.com/mostafa/xk6-kafka/releases/tag/v0.23.0) 2 hours ago.
