### ISSUE TITLE
Request to add authentication through oauth bearer token

### ISSUE THREAD

**Issue by AndyKCS** [mostafa/xk6-kafka#300]
We have xk6 setup for performance testing Kafka using TLS certs. However we are currently implementing authentication to kafka using oauth bearer tokens. If I understand correctly, I don't believe authentication with bearer tokens is currently available in xk6. Is it possible to have this added or is it still not supported in the Kafka go library?

**Comment by mostafa** [comment]
Duplicate of #228.

**Comment by AndyKCS** [comment]
Thanks for getting back to me.  I thought the go library may have been updated so wanted to check if this was in the pipeline to be looked at.
