### ISSUE TITLE
Use of xk6-kafka with TS and webpack

### ISSUE THREAD

**Issue by sgkiokas** [mostafa/xk6-kafka#301]
Hi @mostafa! Thanks a lot for all the effort put in that project, it's much appreciate it.

Let me give me a bit of a background around what I am doing. I am combining K6 with TS in order to fetch some already auto-generated protobuf-based code in order to use your extension and produce messages to some topics. To achieve that, I am using TS with webpack and certain k6 extensions declared in my webpack config like:

```
...
    target: 'node',
    externals: {
        k6: 'commonjs k6',
        'k6/http': 'commonjs k6/http',
        'k6/metrics': 'commonjs k6/metrics',
        'k6/trace': 'commonjs k6/trace',
        'k6/crypto': 'commonjs k6/crypto',
    },
```
After I bundle my code, I can simply run `k6 run .\dist\bundle.js` and everything works well.

What I am looking to see is how I can import this kafka extension to my *.ts file. Currently, if I simply do

```
import * as kafka from 'k6/x/kafka';
```

it moans since `xk6-kafka` is not under the node module `@types/k6` which makes perfect sense. Note that I have extended the `k6` binary with the relevant kafka bundle.

Essentially, I was thinking of adding in the aforementioned code something like:

```
    externals: {
        ...
        'k6/x/kafka': 'commonjs k6/x/kafka',
    },
```

Is there any way to bypass that?

Thanks a lot in advance!

**Comment by mostafa** [comment]
Hey @sgkiokas,

You can find the type info here: https://github.com/mostafa/xk6-kafka/blob/main/api-docs/index.d.ts

**Comment by sgkiokas** [comment]
Hi @mostafa,

Thanks for the prompt reply. You are right, webpack doesn't support URLs. The above worked great!

Thanks again!
