### ISSUE TITLE
Error serializing nullable boolean

### ISSUE THREAD

**Issue by francosang** [mostafa/xk6-kafka#302]
Hey!

I have a schema that looks like this:
```json
{
  "type": "record",
  "name": "Name",
  "fields": [
    { "name": "stacked", "type": ["null", "boolean"], "default": null },
    { more fields },
    { more fields },
  ]
}
```

When I try to produce a message containing a boolean value in the `stacked` property, I get this error:
```
 cannot decode textual union: expected: '{'; actual: 'f' for key: "stacked"
```
But it works correctly without the property.

**Comment by mostafa** [comment]
https://github.com/mostafa/xk6-kafka/issues/266#issuecomment-1927254565
