### ISSUE TITLE
Possibility to connect to AWS Glue to get SchemaRegistry data

### ISSUE THREAD

**Issue by horuktaras** [mostafa/xk6-kafka#303]
Hello. 

First of all want to say Thanks you for extension. It looks well developed plugin for resolving my issues. 

For serialize JSON to AVRO i used your examples in repository. But this approach requires storing hard coded schema in a code without versioning. 

Can you provide some extension to SchemaRegistry class allows us connect and get schema from AWS Glue?

**Comment by mostafa** [comment]
@horuktaras Have you tried this example script?
https://github.com/mostafa/xk6-kafka/blob/main/scripts/test_avro_with_schema_registry.js

**Comment by horuktaras** [comment]
@mostafa sure, I attempted this approach, but it didn't work. The backend is configured for schemas that are only connected to Glue, and I encountered numerous errors with this method.

**Comment by mostafa** [comment]
As per [this doc page](https://docs.aws.amazon.com/glue/latest/dg/schema-registry-works.html), AWS provides a [Java](https://github.com/awslabs/aws-glue-schema-registry) SerDe library for Glue, and there is [an open issue](https://github.com/awslabs/aws-glue-schema-registry/issues/43) for requesting multi-language support. I also found out that the AWS SDK for Go includes [a package](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/glue) to interact with AWS Glue. However, this extension uses [srclient](https://github.com/riferrei/srclient) to handle interactions with the Schema Registry and serdes, and it takes significant efforts to add support for yet another schema registry, unless you're willing to take on the challenge.

**Comment by horuktaras** [comment]
@mostafa I will try to create workaround and probably resolve this challenge. Thanks for respond and investigation.
