### ISSUE TITLE
xk6-kafka memory usage increases over time

### ISSUE THREAD

**Issue by t-g-g-k** [mostafa/xk6-kafka#309]
We are using this library to run a 10 minute load test. It works great.

We have another use case. To run a [soak test ](https://grafana.com/blog/2024/01/30/soak-testing/ ) for 72h. We test by deploying in a container running on a Kubernetes cluster.

The issue we have is that the memory use of the container increases too fast for us to run longer tests.

For example, if I run [this](https://github.com/mostafa/xk6-kafka/blob/main/scripts/test_jsonschema_with_schema_registry.js) file, but add the options for 10 vus and 30m duration, the memory of the container goes from 3mb to 429mb within 30m, and close to 1gb after an hour. Running a 72h soak test doesn't seem possible with the speed that the memory increases.

Is this library designed for longer running tests? 
Is it only designed for load tests?
Are there any options I can use to decrease the memory usage so we could run the test for 72h?

We have tried optimizing the script using the following links:
https://grafana.com/docs/k6/latest/testing-guides/running-large-tests/
https://grafana.com/blog/2021/09/20/load-testing-kafka-producers-and-consumers/

but have not been successful in reducing the memory usage.

Thank you,
Travis

**Comment by t-g-g-k** [comment]
Hi mostafa,

Thank you for the quick response. I am new to k6 and Kafka. I want to confirm I understand your question.

1. Are you asking how many schemas we are using in the test? I am using the file "test_jsonschema_with_schema_registry.js" and all I have changed is the endpoints for the broker and schema registry. So in this case, we are using 2 schemas, keySchemaObject  and valueSchemaObject, which means there would be 2 entries in the cache?

2. Or are you asking how many schema entries we have in our cluster? If there were 1000 entries, the library would cache all of them? and to reduce memory, I should reduce the entries in our schema registry that we aren't using in our test?

Thank you

**Comment by mostafa** [comment]
The extension only caches the schemas used in the test, not all of the ones stored on schema registry. In your case, if you only used the provided schemas, they will be ones stored in memory. However, AFAIK and I asked the k6 team, each instance of the extension runs per VU, hence there is a new instance of the cache per each VU, which might partially explain the memory increase.

**Comment by t-g-g-k** [comment]
Hi mostafa,

Thank you for looking into it and the detailed explanation. I appreciate it.
