### ISSUE TITLE
Add an "official" docker image

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [mostafa/xk6-kafka#32]
Hello, 
I understand that i can manually download and build the plugin, but it would be MUCH better developer experience if you provide a docker image that already does that.

**Comment by AbdelrhmanHamouda** [comment]
@mostafa , I have built this plugin custom binary into a docker image using `szkiba/xk6bundler` and the generated dockerfile from that. 
If that of interest to you, i can open a PR with this to include it in your project.

**Comment by mostafa** [comment]
Hey @AbdelrhmanHamouda!

There's now an [official Docker image](https://hub.docker.com/r/mostafamoradian/xk6-kafka), as you requested.

**Comment by AbdelrhmanHamouda** [comment]
Thanks @mostafa, this is very helpful.
