### ISSUE TITLE
A feature request for access Kafka write & read metric counters

### ISSUE THREAD

**Issue by orxibi** [mostafa/xk6-kafka#33]
Hello,
I'm using K6 for testing Kafka clusters before migration plan. 
And I need to be able to set a limit to the test based on one of the of the k6 Kafka metrics that are used in the summary report.
For example setting up threshold when kafka.writer.message,bytes = 1GB, enabling an access to these metrics will help me make it happened.

**Comment by mostafa** [comment]
With the changes in #31 and the usage of the new k6 metrics API, you can use thresholds on the exported metrics, as shown below and in [this commit](https://github.com/mostafa/xk6-kafka/commit/e1a810d52112f05d7a66c12740d9885ebb64897e).

https://github.com/mostafa/xk6-kafka/blob/e1a810d52112f05d7a66c12740d9885ebb64897e/scripts/test_json.js#L21-L27

So I consider this solved. Also, please keep an eye on #23 if you want to access the rest of the metrics published by [kafka-go](https://github.com/segmentio/kafka-go).
