### ISSUE TITLE
K6 for Confluent kafka

### ISSUE THREAD

**Issue by amir4929** [mostafa/xk6-kafka#35]
Hello,

How can we execute load testing for confluent cloud kafka?

**Comment by mostafa** [comment]
Hey @amir4929,

I've never done this myself, but I think you can do that by setting [the bootstrap server addresses](https://github.com/mostafa/xk6-kafka/blob/57dfc78d0b9c85557519772c3bce7e5f17ed3b30/scripts/test_json.js#L11) to the ones Confluent gave you.

**Comment by amir4929** [comment]
@mostafa Thanks for the info. any idea how we can pass the auth for the confluent bootstrap server?

**Comment by mostafa** [comment]
@amir4929 There is an example of SASL PLAIN and SCRAM authentication in [test_sasl_auth.js](https://github.com/mostafa/xk6-kafka/blob/master/scripts/test_sasl_auth.js). For other examples, have a look at the [scripts](https://github.com/mostafa/xk6-kafka/tree/master/scripts).

**Comment by amir4929** [comment]
@mostafa Thanks

**Comment by mostafa** [comment]
I'll close this issue if you have no more questions. Feel free to open the thread if you have any.
