### ISSUE TITLE
Changes to TLS config broke backward compatibility

### ISSUE THREAD

**Issue by mostafa** [mostafa/xk6-kafka#57]
Based on this [comment](https://github.com/mostafa/xk6-kafka/issues/56#issuecomment-1121182670) from @thanapat-sk, it seems that TLS config is broken. I suspect it is related to this config variable, and it should include a basic TLS config like before.
https://github.com/mostafa/xk6-kafka/blob/8e1fb0c203ee4bcac6e833d908d8d05d2b6bba75/auth.go#L96-L99

@thanapat-sk Do you have any comments, sample code or any console log. It would be much appreciated if you provide more context. 🙏

**Comment by thanapat-sk** [comment]
@mostafa I used to `test_sasl_auth.js` with confluence kafka and get failed but I connected to local kafka then it' work.
so you should to try connect with confluence kafka for get problem.

**Comment by mostafa** [comment]
Released in [v0.11.0](https://github.com/mostafa/xk6-kafka/releases/tag/v0.11.0).
