### ISSUE TITLE
Does Schema Registry support TLS?

### ISSUE THREAD

**Issue by oscar067** [mostafa/xk6-kafka#68]
It should be possible to configure the schema registry using https.

Current http client do not support any kind of certificate configuration

**Comment by mostafa** [comment]
@oscar067 

Thanks for reporting the issue. I'll test and see how it can be fixed. In the meantime, if you have any suggestions on how to fix it, I'd be happy to review your PR.

**Comment by oscar067** [comment]
Opened issue also in riferrei schema registry library https://github.com/riferrei/srclient/issues/80

**Comment by mostafa** [comment]
@oscar067 I think it already supports TLS by passing a custom TLS-enabled HTTP Client to the `CreateSchemaRegistryClientWithOptions` function, but I haven't implemented it in xk6-kafka yet.

**Comment by mostafa** [comment]
I've added it to the to-do list on the [project board](https://github.com/users/mostafa/projects/1/views/1).

**Comment by oscar067** [comment]
Many Thanks @mostafa I'll give you feedback asap
