### ISSUE TITLE
unknown module Error

### ISSUE THREAD

**Issue by yorkmena** [mostafa/xk6-kafka#7]
Getting below error while running the k6 script mentioned in the Readme using this command:
`./k6 run script.js`

Build k6 with xk6 using below command:
`./xk6 build --with github.com/mostafa/xk6-kafka`

**Error**: 
```
ERRO[0001] GoError: unknown module: k6/x/kafka
	at reflect.methodValueCall (native)
	at file:///home/ashish_22484/xk6_compiled/rtddkafka.js:55:47(22)  hint="script exception"
```

**OS**: Amazon linux2
**go version**:  go1.15.8 linux/amd64

& same on

**OS**: OSx Bigsur
**go version** :go1.14.15 darwin/amd64

**Comment by MStoykov** [comment]
hi @yorkmena,
Due to [recent changes to the path of the k6 repo](https://github.com/k6io/k6/issues/1921) all extensions, including this one, needed an update, [which was done](https://github.com/mostafa/xk6-kafka/pull/6), but no new version of the extension was released so by default `xk6` will use an older version :(.

To fix it you can just run `xk6 build --with github.com/mostafa/xk6-kafka@bb0ceb8` which will build with the commit that has the fix.

Hope this helps and that @mostafa will tag a release soon ;)

**Comment by yorkmena** [comment]
Yes it worked like a charm. Thanks :)

**Comment by mostafa** [comment]
Thanks @MStoykov for the fix and the comment.

@yorkmena I've drafted a released as [v0.2.0](https://github.com/mostafa/xk6-kafka/releases/tag/v0.2.0).

**Comment by Schachte** [comment]
I'm still getting this problem .

time="2021-07-27T18:42:18Z" level=error msg="unknown module: k6/x/kafka\n\tat reflect.methodValueCall (native)\n\tat file:///home/scripts/test_json.js:65:65(26)\n" hint="script exception"

```
go version go1.16.4 linux/amd64
```

@MStoykov any suggestions?

**Comment by mostafa** [comment]
@Schachte
You are probably trying to use the k6 installed on your system, rather than the xk6 compiled one that is available in the same directory you tried to build the extension in. This is the log of my build:
```shell
$ xk6 build --with github.com/mostafa/xk6-kafka@latest
2021/07/28 09:58:34 [INFO] Temporary folder: /tmp/buildenv_2021-07-28-0958.404706834
2021/07/28 09:58:34 [INFO] Writing main module: /tmp/buildenv_2021-07-28-0958.404706834/main.go
2021/07/28 09:58:34 [INFO] Initializing Go module
2021/07/28 09:58:34 [INFO] exec (timeout=10s): ~/.gvm/gos/go1.16/bin/go mod init k6 
go: creating new go.mod: module k6
go: to add module requirements and sums:
	go mod tidy
2021/07/28 09:58:34 [INFO] Pinning versions
2021/07/28 09:58:34 [INFO] exec (timeout=0s): ~/.gvm/gos/go1.16/bin/go get -d -v go.k6.io/k6 
go: downloading go.k6.io/k6 v0.33.0
go: downloading github.com/fatih/color v1.11.0
go: downloading golang.org/x/net v0.0.0-20210428185458-6f5299370f2b
go: downloading github.com/klauspost/compress v1.12.2
go: downloading google.golang.org/grpc v1.37.1
go: downloading github.com/tidwall/gjson v1.8.0
go: downloading github.com/golang/snappy v0.0.3
go get: added go.k6.io/k6 v0.33.0
2021/07/28 09:58:47 [INFO] exec (timeout=0s): ~/.gvm/gos/go1.16/bin/go get -d -v github.com/mostafa/xk6-kafka@latest 
go: downloading github.com/mostafa/xk6-kafka v0.4.0
go get: added github.com/mostafa/xk6-kafka v0.4.0
2021/07/28 09:58:55 [INFO] Build environment ready
2021/07/28 09:58:55 [INFO] Building k6
2021/07/28 09:58:55 [INFO] exec (timeout=0s): ~/.gvm/gos/go1.16/bin/go mod tidy 
2021/07/28 09:58:55 [INFO] exec (timeout=0s): ~/.gvm/gos/go1.16/bin/go build -o ~/personal/xk6-kafka/k6 -ldflags -w -s -trimpath 
2021/07/28 09:59:22 [INFO] Build complete: ./k6
2021/07/28 09:59:22 [INFO] Cleaning up temporary folder: /tmp/buildenv_2021-07-28-0958.404706834
``` 
And this is the result:
```shell
$ ls
assets   avro.go           consumer.go  go.mod  **k6**       producer.go  schemaRegistry.go  stats.go
auth.go  configuration.go  errors.go    go.sum  LICENSE  README.md    scripts            topic.go
```
So, if I use this command, it'll run with the compiled xk6-kafka extension and as you see it'll raise an error, because I don't have Kafka running:
```shell
$ ./k6 run scripts/test_json.js 

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: scripts/test_json.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

**Failed to write message: dial tcp [::1]:9092: connect: connection refused[...]**

running (00m00.8s), 0/1 VUs, 0 complete and 1 interrupted iterations
default ✗ [--------------------------------------] 1 VUs  00m00.8s/10m0s  0/1 iters, 1 per VU
WARN[0001] No script iterations finished, consider making the test duration longer 

     ✗ is sent
      ↳  0% — ✓ 0 / ✗ 100

     █ teardown

     checks.........................: 0.00% ✓ 0   ✗ 100
     data_received..................: 0 B   0 B/s
     data_sent......................: 0 B   0 B/s
     iteration_duration.............: avg=434.53µs min=434.53µs med=434.53µs max=434.53µs p(90)=434.53µs p(95)=434.53µs
     kafka.writer.dial.count........: 0     0/s
     kafka.writer.error.count.......: 0     0/s
     kafka.writer.message.bytes.....: 0 B   0 B/s
     kafka.writer.message.count.....: 0     0/s
     kafka.writer.rebalance.count...: 0     0/s
     kafka.writer.write.count.......: 0     0/s
```

**Comment by Schachte** [comment]
@mostafa Perfect, once I reference the binary from my gopath, it seems? to be correct, but I can't get past this error:
```
ERRO[0000] TypeError: Value is not an object: undefined
```

when running this SASL test.

**Comment by mostafa** [comment]
@Schachte 
The `lensesio/fast-data-dev` image doesn't support SASL, instead follow the instructions I outlined in this [commit message](https://github.com/mostafa/xk6-kafka/commit/c35da2da725e9f5e31605e2733ec1c46ff71347b). Plus, if you can give me an excerpt of your script, I'd be more than happy to help.

**Comment by anuj-sharma-ibm** [comment]
hi , If we have to use two binaries 
For example **our custom go extension & other xk6 extension** 
then getting a problem one binary is replaced by other

**Comment by mostafa** [comment]
@anuj-sharma-ibm 
You can pass multiple `--with repo-address` to `xk6` command, and you'll have one binary with multiple extensions compiled into it.

**Comment by mostafa** [comment]
@ShabdaDev 
You are probably trying to run the k6 binary you installed on your system, rather than the one you built with xk6.
Trying running `./k6 run kafka.js` in the same directory you run `xk6`.
