### ISSUE TITLE
Create topic method is unable to determine Controller broker.

### ISSUE THREAD

**Issue by failytaler** [mostafa/xk6-kafka#80]
When I am connecting to Kafka using bootstrap address, during creation of topic I get `Error = [41] Not Controller when creating topic `. When I put all broker addresses manually and pick proper leader - it is able to complete the task. Coud you take a look on [this](https://pkg.go.dev/github.com/segmentio/kafka-go#Conn.Controller) doc and elaborate a bit if the issue can be solved?

**Comment by mostafa** [comment]
@failytaler It's a bug and I'll publish a fix soon.

**Comment by mostafa** [comment]
@failytaler Please build the `main` branch locally and test if it is fixed, using these commands:
```bash
git clone git@github.com:mostafa/xk6-kafka.git && cd xk6-kafka
xk6 build --with github.com/mostafa/xk6-kafka@latest=.
./k6 run yourscript.js
```

**Comment by mostafa** [comment]
Feel free to reopen this issue if the problem persists.
