### ISSUE TITLE
Add support for loading JKS files

### ISSUE THREAD

**Issue by mostafa** [mostafa/xk6-kafka#83]
For configuring Kafka with SSL, we need JKS files. Still, private keys and certificates in PEM format are currently supported, which means the user needs to extract the keys and certificates manually from the JKS files using the `keytool` application and then convert them to be able to use them with the extension. This feature helps alleviate all these steps. Based on my initial investigation, the [keystore-go](https://github.com/pavlo-v-chernykh/keystore-go) can be a viable candidate for quickly adding the feature.

Note to self:
Answer [this person on SO](https://stackoverflow.com/questions/72261550/how-to-work-with-jks-files-in-golang-kafka-go) when you resolved the issue.

**Comment by Rajat01** [comment]
It would be great to have this feature. Right now, like many others even I am facing a hard time converting jks files to pem and then passing through the config.

**Comment by Shabda1988** [comment]
yes please have this feature as part of xk6 kafka . It's bit confusing and difficult to work with jks files and converting them and then using them :(

**Comment by mostafa** [comment]
@Shabda1988 @Rajat01 

I am working on it.

**Comment by Shabda1988** [comment]
> @Rajat01 @Shabda1988 I merged the changes and it is available on the `main` branch. Can you test it with these [instructions](https://github.com/mostafa/xk6-kafka#emitted-metrics)?

Hi @mostafa  To use this should i make a new build of xk6 kafka ? Can i get it from here:  https://k6.io/docs/extensions/get-started/bundle/ ?

**Comment by mostafa** [comment]
@Shabda1988 

Correct, because I haven't released it yet, and just merged it to main, as part of [the release process](https://github.com/mostafa/xk6-kafka#the-release-process). The k6 builder you linked only builds the latest tagged version. If you want to build the changes on the main branch, you must clone the repository locally and use [these instructions](https://github.com/mostafa/xk6-kafka#build-for-development) to build it, as dubbed "Build for development". Sorry for pointing to the wrong link. I corrected it here and in my original message above.

**Comment by mostafa** [comment]
@Shabda1988 You can use the example I provided along with the other scripts. Also, only JKS store type is supported, so PKCS#12 (or .p12) is not supported by the JKS code.

Can you paste your script here, so I can see what you are talking about? Please remove sensitive information.
